export interface IAssociateVehicle {
    ac: number;
    ez: string;
    id: number;
    vin: string;
    make: string;
    uuid: string;
    doors: number;
    model: string;
    lastHu: string;
    origin: number;
    numKeys: number;
    sunRoof: number;
    category: number;
    coupling: number;
    euroNorm: string;
    fuelType: number;
    numSeats: number;
    createdAt: string;
    deletedAt: string | null;
    updatedAt: string;
    dataSource: number;
    externalId: string | null;
    hasDamages: boolean;
    headlights: number;
    isRollable: boolean;
    navigation: number;
    upholstery: number;
    co2Emission: {
        nedc: number;
        wltp: number;
    };
    hadAccident: boolean;
    mileageInKm: number;
    dataWarnings: number[];
    licensePlate: string | null;
    numPreOwners: number;
    readyToDrive: number;
    sportPackage: number;
    transmission: number;
    bodyColorCode: number;
    vehicleHeater: number;
    additionalInfo: string | null;
    huReportExists: boolean;
    sourceLanguage: string;
    commercialUsage: any[];
    datBaseModelRaw: string | null;
    enginePowerInHp: number;
    engineSizeInCcm: number;
    fuelConsumption: any;
    hasEndorsements: boolean;
    isIntendedUse01: boolean;
    urlToMotorSound: string | null;
    vatIdReportable: boolean;
    isVehicleClassN1: boolean;
    urlToAttachment1: string | null;
    urlToAttachment2: string | null;
    urlToAttachment3: string | null;
    huReportAvailable: number;
    isOdometerInMiles: boolean;
    parkingAssistance: number;
    damagesDescription: string | null;
    dimensionWidthInCm: number | null;
    hasMaintenanceBook: boolean;
    unloadedWeightInKg: number | null;
    accidentDescription: string | null;
    dimensionHeightInCm: number | null;
    dimensionLengthInCm: number | null;
    isReimportedVehicle: boolean;
    readyToDriveDetails: string;
    fullServiceHistoryType: number;
    isCocDocumentAvailable: boolean;
    isDataExcerptAvailable: boolean;
    urlsByLanguageToExpose: Record<string, string>;
    fieldsConfirmationStatus: Record<string, number>;
    urlToVehicleSummarySheet: string;
    countryOfLastRegistration: string;
    lastServiceInspectionDate: string;
    serviceHistoryAvailability: number;
    lastServiceInspectionMileage: number;
    damages: any[];
    vehicleImages: {
        url: string;
        perspective: number;
    }[];
    paintState: any[];
    tires: any[];
    technicalState: any[];
    equipmentData: any[];
    equipmentHighlights: any[];
}

/**
 * An interface describing an Auction object from the CarOnSale API.
 */
export interface IAuction {
    id?: number;
    label?: string;
    endingTime?: string;
    state?: number;
    minimumRequiredAsk?: number;
    currentHighestBidValue?: number;
    numBids?: number;
    locationAddress?: string | null;
    locationCity?: string;
    locationZip?: string;
    startedAt?: string;
    createdAt?: string;
    updatedAt?: string;
    hotBid?: boolean;
    originalMinimumRequiredAsk?: number | null;
    allowInstantPurchase?: boolean;
    instantPurchasePossibleUntil?: string | null;
    advertisementHtmlContent?: string | null;
    instantPurchasePrice?: number | null;
    locationCountryCode?: string;
    startingBidValue?: number;
    uuid?: string;
    _fk_uuid_vehicle?: string;
    _fk_uuid_sellerUser?: string;
    _fk_uuid_highestBiddingBuyerUser?: string | null;
    urlToPickupBuyerDocument?: string | null;
    paymentProcess?: number;
    type?: number;
    _fk_uuid_creatingSellerUser?: string | null;

    isTest?: boolean;
    displayMinAsk?: boolean;
    isLive?: boolean;
    isTransportationDisabledManually?: boolean;
    startingBidValueNet?: number;
    minimumRequiredAskNet?: number;
    originalMinimumRequiredAskNet?: number | null;
    purchasePriceNet?: number;
    currentHighestBidValueNet?: number;
    highestBidValueAtEndingTimeNet?: number | null;
    instantPurchasePriceNet?: number | null;
    lastOfferBySellerNet?: number | null;
    previousLastOfferBySellerNet?: number | null;
    counterOfferByBuyerNet?: number | null;
    previousCounterOfferByBuyerNet?: number | null;
    renegotiationMidpointValueNet?: number | null;
    pickupInstructions?: string | null;
    thirdPartyVATDepositTransferReference?: string | null;
    thirdPartyVatTransferReference?: string | null;
    thirdPartyVATDepositRefundReference?: string | null;
    preventSellerFactoring?: boolean;
    listingSurchargeFeeInvoiceReference?: string | null;
    additionalTaxType?: number;
    additionalTaxValue?: number | null;
    isVATReportable?: boolean;
    thirdPartyVATDepositReversalReference?: string | null;
    uploadMethod?: number;
    additionalTaxExportDiscount?: number;
    isCosCheckPlusGuaranteeEnabled?: boolean;
    isExtendedGuaranteeEnabled?: boolean;
    bookedServicesInvoiceReference?: string | null;
    directUploadRejectionReasons?: any[];
    readyToBeReinsertedSince?: string | null;
    externalRenegotiationTicketUuid?: string | null;
    urlToCoverLetter?: string | null;
    sellerToCosInvoiceUrlFirstUploadedAt?: string | null;
    thirdPartyCorrectionInvoiceReference?: string | null;
    urlToCorrectionInvoice?: string | null;
    reauctionedWaitingForBuyerPaymentAt?: string | null;
    isReauction?: boolean;
    reauctionedMergedAt?: string | null;
    sellerViewHighestBidValue?: number | null;
    sellerViewPurchaseConfirmedAt?: string | null;
    biddingAgentValue?: number;
    didIBidAtLeastOnce?: boolean;
    isParked?: boolean;
    remainingTimeInSeconds?: number;
    remainingTimeForInstantPurchaseInSeconds?: number | null;
    associatedVehicle?: IAssociateVehicle;

    amIInvolved?: boolean;
    amIHighestBidder?: boolean;
    sellerContact?: null | unknown;
    rating?: null | unknown;
    isTransportationAllowedForRegion?: boolean;
    isExternalPaymentAllowed?: boolean;
    remainingDaysUntilReauctioning?: null | unknown;
    remainingDaysUntilLatePickup?: null | unknown;
    latePickupFee?: null | unknown;
    isTransportationBookingPossible?: boolean;
    isExpressPickupAvailable?: boolean;
    pickupPossibleInDays?: null | unknown;
    sellerAccount?: {
        shouldApplyStandingCosts: boolean;
        isCompoundEnabled: boolean;
    };
    amIRegularBuyer?: boolean;
    isCrossBorderNetSale?: boolean;
    buyerPurchaseFee?: number;
    buyerSuccessFee?: number;
    vatAmount?: number;
    vatRate?: number;
    complaintPeriodEndAt?: null | unknown;
    transportBookingPeriodEndAt?: null | unknown;
    isCompoundPickup?: boolean;
    hasIncreasedPickupTime?: boolean;
    buyerCrossBorderProcessingAmount?: number;
    isRecommended?: boolean;
    sellerType?: number;
    transportationTask?: null | unknown;
    enforceTransportation?: boolean;
    isTransportationAvailable?: boolean;
    isMinAskReached?: boolean;
    isWatching?: boolean;
    biddingAgentValueNet?: null | unknown;
    distanceToVehicleInKms?: number;
    hasNextAuction?: null | unknown;
    hasPreviousAuction?: null | unknown;
}
